test top level usage

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -28,3 +28,57 @@ jobs:
   test:
     uses: ./.github/workflows/test.yml
     needs: validate-dist
+
+  test-top-level:
+    needs: validate-dist
+    runs-on: ubuntu-latest
+    steps:
+      - name: Get job workflow
+        id: job-workflow
+        uses: jenseng/dynamic-uses@v1
+        with:
+          uses: jenseng/get-job-workflow@${{ github.sha }}
+      - name: Assert repository
+        env:
+          expected_repository: ${{ github.repository }}
+          actual_repository: ${{ fromJSON(steps.job-workflow.outputs.outputs).repository }}
+        shell: bash
+        run: |
+          if [[ "$expected_repository" != "$actual_repository" ]]; then
+            echo "::error::Expected repository: $expected_repository"
+            echo "::error::Actual repository: $actual_repository"
+            exit 1
+          fi
+      - name: Assert path
+        env:
+          expected_path: .github/workflows/cicd.yml
+          actual_path: ${{ fromJSON(steps.job-workflow.outputs.outputs).path }}
+        shell: bash
+        run: |
+          if [[ "$expected_path" != "$actual_path" ]]; then
+            echo "::error::Expected path: $expected_path"
+            echo "::error::Actual path: $actual_path"
+            exit 1
+          fi
+      - name: Assert ref
+        env:
+          expected_ref: ${{ github.ref }}
+          actual_ref: ${{ fromJSON(steps.job-workflow.outputs.outputs).ref }}
+        shell: bash
+        run: |
+          if [[ "$expected_ref" != "$actual_ref" ]]; then
+            echo "::error::Expected ref: $expected_ref"
+            echo "::error::Actual ref: $actual_ref"
+            exit 1
+          fi
+      - name: Assert sha
+        env:
+          expected_sha: ${{ github.workflow_sha }}
+          actual_sha: ${{ fromJSON(steps.job-workflow.outputs.outputs).sha }}
+        shell: bash
+        run: |
+          if [[ "$expected_sha" != "$actual_sha" ]]; then
+            echo "::error::Expected sha: $expected_sha"
+            echo "::error::Actual sha: $actual_sha"
+            exit 1
+          fi
